# Generated by Django 5.0.6 on 2024-06-20 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sucursal', verbose_name='Sucursal'),
        ),
    ]
