# Generated by Django 5.0.6 on 2024-06-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_producto_descuento_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='fecha_fin',
            field=models.DateField(default='2024-01-02'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='fecha_inicio',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='productos',
            field=models.ManyToManyField(related_name='promociones', to='api.producto'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('bodeguero', 'Bodeguero'), ('contador', 'Contador')], default='admin', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='descuento',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
