# Generated by Django 5.0.6 on 2024-06-21 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_promocion_fecha_fin_promocion_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descuento',
        ),
    ]
