# Generated by Django 5.0.6 on 2024-06-21 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_subtotal_detalleventa_precio_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='tipo_documento',
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.venta'),
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.venta')),
            ],
        ),
        migrations.CreateModel(
            name='CarroDeCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.venta')),
            ],
        ),
    ]
