# Generated by Django 5.0.6 on 2024-06-21 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_cliente_direccion_cliente_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.promocion'),
        ),
    ]
