# Generated by Django 5.0.6 on 2024-06-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_producto_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='descuento_aplicado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
