# Generated by Django 5.0.6 on 2024-06-21 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_detalleventa_descuento_aplicado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notacredito',
            name='motivo',
        ),
        migrations.AddField(
            model_name='notacredito',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notacredito',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.venta'),
        ),
    ]
