# Generated by Django 5.0.6 on 2024-06-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_notacredito_motivo_notacredito_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='entregado',
            field=models.BooleanField(default=False, verbose_name='Entregado'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
