# Generated by Django 5.0.6 on 2024-06-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_venta_entregado_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='fecha_emision',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateTimeField(null=True),
        ),
    ]
