# Generated by Django 5.0.6 on 2024-06-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_boleta_fecha_emision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=20, unique=True)),
                ('ultimo_numero', models.IntegerField(default=0)),
            ],
        ),
    ]
